import '../index.css';

export const styleDesktop = {
    header: {
        fontFamily: 'PoiretOne, cursive',
        fontSize: 'x-large',
        textShadow: '0 0 6px #ffb8f1',
        fontWeight: 'bold',
        color: 'white',
        width: '100%',
        height: '15%',
        borderWidth: 'thick',
        borderStyle: 'double',
        borderColor: '#fffbff',
        borderBottomLeftRadius: '50px',
        borderBottomRightRadius: '50px',
        backgroundColor: 'rgba(128,0,128,0.5)',
        padding: '0.5% 0.5% 0.5% 3%'
    },
    clock: {
        borderColor: 'yellow',
        borderStyle: 'dashed',
        borderRadius: '50px',
        textShadow: '0 0 6px yellow',
        backgroundColor: '#ff7de8',
        'vertical-align': 'center',
        fontSize: '120px',
        color: 'black',
        marginTop: '1%',
        marginLeft: '10%',
        width: '35%',
        textAlign: 'center',
    },
    kitten:{
        marginLeft: '55%',
        marginTop: '-25%',
        size: '50%'
    },
    sign: {
        fontSize: '10pt',
        color: 'white',
        position: 'absolute',
        bottom: '0px',
        left: '10px'
    },
    loginField: {
        align: {
            width: '400px',
            height: '250px',
            backgroundColor: 'rgba(63,252,255,0.5)',
            marginLeft: '14.5%',
            marginTop: '1%',
            borderWidth: 'thick',
            borderStyle: 'double',
            borderColor: '#fffbff',
            borderRadius: '50px',
            padding: '1%',
            boxShadow: '0 0 6px',
        },
        userAnswer:{
            color: 'black',
            fontSize: '15pt',
            marginTop: '10pt',
            textAlign: 'left',
            marginLeft: '40pt'
        },
        textField: {
            width: '95%',
            borderRadius: '20px',
            paddingLeft: '2%',
            borderColor: 'black',
            marginTop: '4%',
            fontSize: 'medium',
        },
        button: {
            cursor: 'pointer',
            padding: '10px',
            width: '120px',
            marginTop: '10px',
            marginLeft: '20px',
            marginRight: '20px',
            borderRadius: '30px',
            borderColor: 'black',
            backgroundImage: '-webkit-linear-gradient(left, yellow, palevioletred)',
            boxShadow: '0 0 6px grey',
            fontWeight: 'bold',
            fontSize: 'large',
            fontFamily: 'Jura, sans-serif',
        },
    },
    base: {
        fontFamily: 'Jura, sans-serif',
    },
    cat: {
        marginLeft: '10%',
    },
    graph: {
        position: 'absolute',
        right: '3%',
        top: '20%',
        borderWidth: 'thick',
        borderStyle: 'double',
        borderColor: '#fffbff',
        borderRadius: '50px',
        padding: '0.4%',
        boxShadow: 'inset 0 0 6px',
    },
    xyr_in: {
        width: '600px',
        height: '250px',
        backgroundColor: 'rgba(63,252,255,0.5)',
        marginLeft: '3%',
        marginTop: '-13%',
        borderWidth: 'thick',
        borderStyle: 'double',
        borderColor: '#fffbff',
        borderRadius: '50px',
        padding: '1%',
        boxShadow: '0 0 6px',
    },
    form: {
        x_in: {
            marginLeft: '0.5%',
            marginTop: ' 0.5%',
            width: '48%',
            height: '45%',
            borderStyle: 'double',
            borderColor: 'white',
            backgroundColor: '#ff7de8',
            borderTopLeftRadius: '50px',
            textAlign: 'left',
            padding: '1%',
            float: 'left',
            boxShadow: 'inset 0 0 6px',
        },
        chooseX: {
            marginLeft: '55%',
        },
        slider: {
            marginTop: '8%',
            marginLeft: '5%',
            marginRight: '5%',
        },
        y_in: {
            width: '48%',
            height: '45%',
            borderStyle: 'double',
            borderColor: 'white',
            backgroundColor: '#ff7de8',
            borderTopRightRadius: '50px',
            textAlign: 'left',
            'padding': '1%',
            'float': 'right',
            marginTop: '0.5%',
            marginRight: '0.5%',
            boxShadow: 'inset 0 0 6px',
        },
        chooseY: {
            marginLeft: '5%',
        },
        r_in: {
            width: '48%',
            height: '45%',
            borderStyle: 'double',
            borderColor: 'white',
            backgroundColor: '#ff7de8',
            borderBottomLeftRadius: '50px',
            padding: '1%',
            float: 'left',
            textAlign: 'left',
            marginTop: '2.5%',
            marginLeft: '0.5%',
            boxShadow: 'inset 0 0 6px',
        },
        chooseR: {
            marginLeft: '55%',
        },
        send_form: {
            width: '48%',
            height: '45%',
            borderStyle: 'double',
            borderColor: 'white',
            backgroundColor: '#ffb8f1',
            borderBottomRightRadius: '50px',
            'float': 'right',
            marginTop: '2.5%',
            marginRight: '0.5%',
            paddingTop: '4%',
            paddingLeft: '14%',
            boxShadow: 'inset 0 0 6px',
        },
        send_button: {
            cursor: 'pointer',
            padding: '10px',
            width: '120px',
            marginRight: '40%',
            borderRadius: '30px',
            borderColor: 'black',
            backgroundImage: '-webkit-linear-gradient(left, yellow, palevioletred)',
            boxShadow: '0 0 6px grey',
            fontWeight: 'bold',
            fontSize: 'large',
            fontFamily: 'Jura, sans-serif',
        }
    },
    logout_button: {
        position: 'absolute',
        cursor: 'pointer',
        padding: '10px',
        width: '120px',
        borderRadius: '30px',
        borderColor: 'black',
        backgroundImage: '-webkit-linear-gradient(left, yellow, palevioletred)',
        boxShadow: '0 0 6px grey',
        right: '2%',
        top: '5%',
        fontWeight: 'bold',
        fontSize: 'large',
        fontFamily: 'Jura, sans-serif',
    },
    result: {
        marginLeft: '3%',
        marginTop: '3%',
        textAlign: 'center',
        'border': 'solid 1px white',
        backgroundColor: '#ffbe52',
    },
    result_head: {
        backgroundColor: 'yellow',
        textAlign: 'center',
        width: '110px',
        height: '30px',
        'border': 'solid 1px white',
        borderCollapse: 'collapse',
    }
}
